### ISSUE TITLE
Crash safety while writing to the log

### ISSUE THREAD

**Issue by tezc** [RedisLabs/redisraft#127]
Do some crash tests while writing to the log. At least handle half written log entry. Consider adding CRC32 hash to the log files/entries. 

Also, create a separate file to persist voting and configuration in order to keep the log strictly append only and reduce assumptions about filesystem consistency properties.

**Comment by yossigo** [comment]
@tezc Definitely!

I think this needs to start by defining what guarantees we expect the filesystem to provide. AFAIR ext4 has `data=ordered` by default so worrying about anything more than short writes might not be needed (but crc32 might still be a good idea).

I had some thoughts about syscall instrumentation and fault injection in order to properly test `fsync()`. I remember I also came across a FUSE filesystem that aimed to address a similar case.

**Comment by tezc** [comment]
@yossigo looks like I missed the notification somehow, sorry about that. 

Which fuse impl are you referring to? I couldn't find anything with my terrible google skills. 

I think, if you are writing to the file sequentially, it can be pretty straightforward. On restart, just try to read log file sequentially, on any problem dismiss the rest of the file. 

Things that comes to my mind : 

1. If we are going to support settings other than `data=ordered`, Crc32 might be needed. 
2. Testing half written entry can be easy. e.g trim or extend the log file and restart, write some random data at the end and restart. Verifying if we are using fsync correctly is very hard though :) 
3. How to use fsync : 
    - Write to the file : fsync file
    - All other cases (create, rename, remove ..) : fsync file and directory.

4. If you find a corrupt entry, whether it is at the end or not, you'll never know if it was a committed entry. Assume, you are the only node in the cluster. You acknowledged entry at index 10, client got the response. Node crashes and restarts. Node sees entry at index 10 has wrong crc32 value or it's just half written. This can be a disk issue(bit rot etc) or just a crash on fsync. Node starts without entry 10, that operation is now lost. (Raft considers disk issues as Byzantine faults and raft does not handle byzantine faults). I saw some implementations provide an option for paranoid users to refuse to start the server on this case, leaving it to the administrator. Most others just dismiss rest of the file (I believe this is the sane option). 

5. Right now, we are writing to the head of the log file on term and vote update. If it crashes while updating header, we might lose all the logs probably(I'm not sure here?). An alternative implementation is maintaining a separate metadata file. This file can contain term, vote and also latest configuration from the log. So, as a bonus, we don't need to scan the log to find latest configuration on restart. It's on the file all the time. Anyway, by maintaining another metadata file, we'll be writing to the log sequentially and avoid that corruption scenario if I'm not mistaken.

These are random things that comes to my mind, some or all might be wrong :)

**Comment by yossigo** [comment]
@tezc
The filesystem I was referring to is this: https://github.com/scylladb/charybdefs

Some other thoughts:

* Half written entries should already be handled well because of the way they're serialized to disk. I think it's even covered by unit tests and if not - should be a trivial thing.

* I think `fsync()` is done on the file but not on the directory right now, so this might need fixing. One strategy I was considering for testing `fsync()` was to override it (with `LD_PRELOAD`) with a mockup that tracks what was fsynced, then inject random faults where we terminate the process and truncate to the last fsync'd offset. I think this can work pretty well for files, not sure about directories though.

* I fully support the idea of rejecting a corrupt log altogether. From an operations perspective, it might make sense to have a tool that can clean up such a log so an admin can decide to manually recover after considering what data is corrupted or lost.

* As far as I can tell, rewriting the log header should not result with corruption because it should be a simple block replacement operation. The main benefit is simplicity - having a single file. If we determine this assumption is wrong and keep this information separately, I think it should still only hold voting information but not configuration which is deduced by loading the snapshot and applying the log. I'm not sure we can avoid scanning the log anyway, because we need to reindex and make sure it is valid (if it's not, we need to abort early).

**Comment by tezc** [comment]
Just for the last bullet point, 

> As far as I can tell, rewriting the log header should not result with corruption because it should be a simple block replacement operation

This is not guaranteed AFAIK but you have to make some assumptions at some point :)

> If we determine this assumption is wrong and keep this information separately, I think it should still only hold voting information but not configuration which is deduced by loading the snapshot and applying the log

I think a more common implementation is placing configuration along with vote and term into that file. So, you update this metadata file whenever
- term changes
- node votes for someone
- a config change is appended to the log or when it's rolled back

Benefit is you don't need to use snapshot + log to find out the latest log on restart. Latest configuration you know is always there in its separate file. This will also avoid some states that exists right now in the raft library, "addition_committed" or "voting_committed" etc or related code in the redisraft itself.

> I'm not sure we can avoid scanning the log anyway, because we need to reindex and make sure it is valid (if it's not, we need to abort early).

Sure, you need to go over the log to see if it's corrupt. I just meant you don't have to worry about rebuilding the latest configuration.

**Comment by yossigo** [comment]
> This is not guaranteed AFAIK but you have to make some assumptions at some point :)

Yes, reconsidering it again it's probably an assumption based on specific implementations rather than something formal (which AFAIK does not exist).

I'll open an issue for that.

**Comment by yossigo** [comment]
Related to #180

**Comment by tezc** [comment]
Update after a year,

1- https://github.com/scylladb/charybdefs is a FUSE file-system. It listens on a port for directives. As this is a separate process and it requires some steps for the setup, it's harder to use compared to an in-process solution (LD_PRELOAD trick mentioned above). 

2- https://github.com/jepsen-io/local-fs
Feels like something that might be useful for us but actually it is for testing file-system implementations. 

3- For the discussion of the context, see: https://lwn.net/Articles/457667/

In summary there are two cases for us: 
- Crash while appending to the file. 
   - We need to be prepared for half written entries.
   - We need to detect corrupt entries.
      - Assume entry is 4kb. You append the entry. Filesystem increases file size. Writes 1 kb and crashes. Can we detect it? (need crc here?)
      
- Crash while creating a new file. 

    From the link above, correct sequence for the crash safety (for the new files): 
    ```
    create a new temp file (on the same file system!)
    write data to the temp file
    fsync() the temp file
    rename the temp file to the appropriate name
    fsync() the containing directory
    ```

    So, one tricky thing about crash-safety is what to do when you create a new file.
    RedisRaft creates a new file:
    - While writing the new metadata file
    - When we take a snapshot
    - When we receive a snapshot
    - When we truncate the log file

    We need to be sure we flush data to the disk correctly for these cases. In summary, we should call fsync() for the directory and for the file itself. 

------

It'd be nice to come up with a tool to test it. (We may write a shared object file and load it to overwrite syscalls to inject error / crashes).
- We can override system calls but need to have a map of `file descriptor->file_name` map and inject errors to the files/calls that we care about. (e.g. fsync(fd) <-- we need to detect that fd is the `fd` we care about.)

**Comment by tezc** [comment]
This should be fixed now.
