### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#134]
Currently RedisRaft assumes it runs on top of Redis using a plain-text TCP port. Add support for cross-node communication using TLS.

**Comment by sjpotter** [comment]
My guess is that this is pretty simple.

1) each redis-server is run with tls setup as appropriate for a normal redis-server

2) each RedisRaft module on each redis-raft server is given equivalent tls setup so that it can instantiate it's local hiredis client appropriately.

What I'm blocked on right now is how to use hiredis with tls appropriately, all the documentation I've found so far (such as example in hiredis code) is for synchronous usage, not asych usage as we would need).
