### ISSUE TITLE
Adding a node with the same id as a previously existing node should be forbidden

### ISSUE THREAD

**Issue by yaeltzirulnikov** [RedisLabs/redisraft#2]
After creating a cluster with 2 nodes,
then running "RAFT.NODE remove 2"
Then running another server (with new log) and uid 2, when trying to run "RAFT.CLUSTER JOIN localhost:5001" the new server crashes with error:
"Assertion failed: (node), function raft_handle_append_cfg_change, file src/raft_server.c, line 1227."

**Comment by gavrie** [comment]
Summarizing the discussion with @yossigo:
- We need to keep a list of all node ids that have ever been members of the cluster.
- The list should survive log compaction so it should be part of the snapshot we maintain in the RDB file.

**Comment by gavrie** [comment]
The original crash no longer occurs with the current codebase. Instead, re-adding the node succeeds initially, until it gets to the point in the log where it sees itself being removed - causing it to terminate.

I've added an integration test that tests this scenario. This behavior is what happens with 3 nodes (of which 1 is removed).

In a 2-node cluster, the re-added node decides to become leader, probably due to the fact that it was previously marked as a voting node.

Both scenarios should be irrelevant once we forbid re-adding the node with the same id.
