### ISSUE TITLE
RedisRaft should enforce ACL rules

### ISSUE THREAD

**Issue by gildaf** [RedisLabs/redisraft#231]
Redis supports [ACL rules](https://redis.io/topics/acl). 
Currently ReidsRaft does not check the ACL rule. 

how to reproduce:
start a redis server with raft module and initialize the raft cluster. 
run 
```bash
ACL SETUSER gil +@all -hset -set  on >mypass
AUTH gil mypass
set x 3
```
The `set` command should have failed, but didnt.

**Comment by sjpotter** [comment]
ACLs are similiar to watch.  we would need the redis module interface to be able to provide us with a "session" capability, so that each node in the cluster operates each command on the proper session.

**Comment by yossigo** [comment]
This would mean we're also pulling ACL configuration into the Raft consensus. This can work, but is not aligned with how Redis Cluster / Master-Replicas handle ACLs today.

Initially, I wanted to propose the alternative where the leader is responsible to apply ACL logic at the level of the user session, before appending operations to the log. This could greatly simplify ACLs, but I see at least one area where it fails: Lua scripts.

**Comment by sjpotter** [comment]
I dont think thinking of raft clusters as redis cluster master/replica as conducive to raft.  they are really a single node cluster, they just sort of look like master/replica due to the leader/follower conception of raft.  i.e. one shouldn't configure nodes independently in a manner that impacts data in and how one accesses the underlying database except if its really node independent configuration.

**Comment by fadidahanna** [comment]
Design Doc: https://docs.google.com/document/d/1IGH2iVwouWLNiSONXtfhXti0sWJuPZhBlga5ooOTkOo/edit
