### ISSUE TITLE
Make membership operations synchronous

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/redisraft#56]
When calling `RAFT.CLUSTER JOIN` or `RAFT.NODE REMOVE`, ideally the user experience should be synchronous and return when the operation completes.

**Comment by sjpotter** [comment]
so first Q.  wondering about the API of CLUSTER JOIN and NODE REMOVE are they supposed to be parallel APIs (i.e. add/remove) or are they functionally different in some way?

second question is, would it be synchronous to turn these into raft log events like any other redis command, so that we only call InitiateJoinCluster() after adding a consistent log entry to the cluster? (or similarly for node removal)

**Comment by yossigo** [comment]
These two commands don't operate at the same level.

We can think of `RAFT.CLUSTER JOIN` as some utility function that basically:
* Sends a `RAFT.NODE ADD` command to the specified node.
* Handles redirection to leader if necessary
* Handles `RAFT.NODE ADD` failures and retries, if necessary.
* Optionally awaits for the local node to join the cluster / receive sufficient logs to become voting (this bit is what this PR is about).

On the other hand, `RAFT.NODE ADD/REMOVE` commands are core commands that:
* Execute on the leader only
* May result with permanent failure (e.g. attempting to add a duplicate node id, remove non-existing node, etc.)
* May result with a temporary failure (e.g. another joint consensus operation is in progress).
* Can follow the same principles and code flows of `RAFT` commands, where the client is blocked and the reply is generated only  at the time where the related Raft log entry is committed.

I guess this answers "yes" to the second question, if I understood it correctly.

**Comment by sjpotter** [comment]
ok, I misunderstood, now getting a better grasp.    RAFT.NODE add (and REMOVE I believe) are synchronous actions a they are change that have to be committed to the raft log.  JOIN is not, as all its doing is add a "virtual" connection of sorts and having the event driven infrastructure handle it.

I'm wondering if it be reasonable to have a "joined" event, and instead of essentially the joining process ending with in handleClusterJoin()

    RedisModule_ReplyWithSimpleString(req->ctx, "OK");
    RaftReqFree(req);

we insert another event callback that somehow has access to the req object, whose event is essentially fired off in HandleClusterJoinCompleted()  which calls the above 2 function calls and returns.

**Comment by yossigo** [comment]
Yes, I think something in this direction is what we'd need.
