### ISSUE TITLE
Performance testing problem

### ISSUE THREAD

**Issue by Wlitsoft** [RedisLabs/redisraft#72]
Hi,
I used a cluster of three machines, each with IOPS of 1432, but I got the low test value of 50-100 Ops/s for Redisraft set. Is this normal?

**Comment by yossigo** [comment]
@Wlitsoft The results you see seem very low. How did you test? Also, what IOPS do you refer to - is that disk IOPS?

Two general comments:
1. You should not expect a RedisRaft to improve its performance as you grow the number of nodes, because they are all replicas. In fact, performance is likely to be slightly worse as the number of machines increase.
2. We have a lot of optimization ideas for RedisRaft which were not implemented yet, so in its current form it's probably still far from optimal.

**Comment by Wlitsoft** [comment]
> @Wlitsoft The results you see seem very low. How did you test? Also, what IOPS do you refer to - is that disk IOPS?
> 
> Two general comments:
> 
> 1. You should not expect a RedisRaft to improve its performance as you grow the number of nodes, because they are all replicas. In fact, performance is likely to be slightly worse as the number of machines increase.
> 2. We have a lot of optimization ideas for RedisRaft which were not implemented yet, so in its current form it's probably still far from optimal.

Yes, it is the IOPS of the hard disk. When raft-log-fsync is yes, the QPS of the test is about 80. When it is no, the performance is the same as that of rediis opening AOF always, both of which are three copies.

**Comment by yossigo** [comment]
I guess the more significant drop is the result of things taking place in serial and being latency bound. That's one of the things we'd like to improve performance wise.
